const productsRoute = require("./Product/productsRoute");
const categoriesRoute = require("./Product/CategoryRoute");
const salesRoute = require("./salesRoute");
const stockTransactionsRoute = require("./Product/StockTransactionsRoute");
const cashTransactionsRoute = require("./CashTransactionsRoute");
const metricsRoute = require("./MetricRoute");
const pluRoute = require("./pluRoute");
const printerRoute = require("./PrinterRoute");
const reportsRoute = require("./reportsRoute");
const categoryRoute = require("./Product/CategoryRoute");
const supplierRoute = require("./Supplier/SupplierRoute");
const supplierTransactionsRoute = require("./Supplier/SupplierTransactions");
const productShortCutRoute = require("./Product/productShortCutRoute");
const router = (app) => {
  app.use("/api/products", productsRoute);
  app.use("/api/product-shortcuts", productShortCutRoute);
  app.use("/api/categories", categoriesRoute);
  app.use("/api/sales", salesRoute);
  app.use("/api/stock-transactions", stockTransactionsRoute);
  app.use("/api/cash-transactions", cashTransactionsRoute);
  app.use("/api/metrics", metricsRoute);
  app.use("/api/plu", pluRoute);
  app.use("/api/printer", printerRoute);
  app.use("/api/reports", reportsRoute);
  app.use("/api/category", categoryRoute);
  app.use("/api/suppliers", supplierRoute);
  app.use("/api/supplier-transactions", supplierTransactionsRoute);
};

module.exports = router;
